# GATE Monte Carlo dose estimation using beta spectrum of  Lu-177 in spherical water phantom #

#---------------------------------------------------------------------#
#                 V E R B O S I T Y                                   #
#---------------------------------------------------------------------#
/gate/verbose Physic    0
/gate/verbose Cuts      0
/gate/verbose SD        0
/gate/verbose Actions   0
/gate/verbose Actor     0
/gate/verbose Step      0
/gate/verbose Error     0
/gate/verbose Warning   0
/gate/verbose Output    0
/gate/verbose Beam      0
/gate/verbose Volume    0
/gate/verbose Image     0
/gate/verbose Geometry  0
/gate/verbose Core      0

/run/verbose 2
/event/verbose 2
/tracking/verbose 2

/gate/geometry/setMaterialDatabase /Users/atiwr/gate_data_files/GateMaterials.db
#----------------------------------------------------------------------#
#                           W O R L D                                  #
#----------------------------------------------------------------------#
/gate/world/geometry/setXLength         10 mm
/gate/world/geometry/setYLength         10 mm
/gate/world/geometry/setZLength         10 mm
/gate/world/setMaterial                 Water

#----------------------------------------------------------------------#
#                  P H A N T O M   G E O M E T R Y                     #
#----------------------------------------------------------------------#
/gate/world/daughters/name              my_phantom
/gate/world/daughters/insert            sphere
/gate/my_phantom/setMaterial            Water

/gate/my_phantom/geometry/setRmax       3.63 mm
/gate/my_phantom/geometry/setRmin       0.   mm
/gate/my_phantom/vis/forceSolid
/gate/my_phantom/vis/setColor           grey
/gate/my_phantom/placement/setTranslation -0.00605 -0.00605 -0.00605 mm
/gate/my_phantom/attachPhantomSD

# sphere radius = dosel size * # of concentric shells

#----------------------------------------------------------------------#
#                   A C T O R S                                        #
#----------------------------------------------------------------------#
/gate/actor/addActor          DoseActor    dosimetry
/gate/actor/dosimetry/attachTo             my_phantom
/gate/actor/dosimetry/stepHitType          random

#/gate/actor/dosimetry/setResolution	   600 600 600
/gate/actor/dosimetry/setPosition          -0.00605 -0.00605 -0.00605 mm
/gate/actor/dosimetry/setSize              7.26 7.26 7.26 mm
/gate/actor/dosimetry/setVoxelSize         0.0121 0.0121 0.0121 mm

/gate/actor/dosimetry/enableDose            false
/gate/actor/dosimetry/enableEdep            true
/gate/actor/dosimetry/enableUncertaintyEdep false
/gate/actor/dosimetry/enableSquaredEdep     false
/gate/actor/dosimetry/save                  test/2e7_177Lu_water.mhd
/gate/actor/dosimetry/saveEveryNSeconds     120

/gate/actor/addActor                        SimulationStatisticActor stat
/gate/actor/stat/save                       output/2e7_177Lu_water.txt
/gate/actor/stat/saveEveryNSeconds          120

#----------------------------------------------------------------------#
#             P H Y S I C S   D E S C R I P T I O N                    #
#----------------------------------------------------------------------#
/gate/physics/addPhysicsList  emstandard_opt3
/gate/physics/addProcess RayleighScattering
/gate/physics/processes/RayleighScattering/setModel PenelopeModel

# ---------------------------------------------------------------------#
#   E L E C T R O M A G N E T I C     O P T I O N S                    #
#----------------------------------------------------------------------#
/gate/physics/setEMin 0.1 keV
/gate/physics/setEMax 10 GeV
/gate/physics/setDEDXBinning   220
/gate/physics/setLambdaBinning 220

/gate/physics/Gamma/SetCutInRegion      world 0.1 mm
/gate/physics/Electron/SetCutInRegion   world 0.005 mm
/gate/physics/Positron/SetCutInRegion   world 0.005 mm

/gate/physics/Gamma/SetCutInRegion      my_phantom 0.1 mm
/gate/physics/Electron/SetCutInRegion   my_phantom 0.003 mm
/gate/physics/Positron/SetCutInRegion   my_phantom 0.003 mm

/gate/physics/SetMaxStepSizeInRegion    my_phantom 0.0121 mm
/gate/physics/ActivateStepLimiter e-
/gate/physics/ActivateStepLimiter gamma

/gate/physics/processes/ElectronIonisation/setStepFunction e- 0.0001  0.001 mm


#----------------------------------------------------------------------#
#                     I N I T I A L I Z E                              #
#----------------------------------------------------------------------#
/gate/run/initialize
/gate/physics/displayCuts
/gate/physics/processList Enabled
/gate/physics/processList Initialized

#----------------------------------------------------------------------#
#     Lu177 Beta spectrum : Discrete spectrum                          #
#----------------------------------------------------------------------#
/control/execute source_beta_gamma_only.mac 
/gate/source/list


#----------------------------------------------------------------------#
#               V I S U A L I S A T I O N                              #
#----------------------------------------------------------------------#
/vis/disable
/vis/open OGL
/vis/viewer/reset
/vis/viewer/set/viewpointThetaPhi 30 60
/vis/viewer/zoom
/vis/viewer/set/style wireframe
/vis/drawVolume
/vis/viewer/flush
/vis/scene/add/trajectories
/tracking/storeTrajectory 1
/vis/scene/add/hits
/vis/scene/endOfEventAction accumulate 10

#-----------------------------------------------------------------------#
#          R A N D O M     G E N E R A T O R                            #
#-----------------------------------------------------------------------#
/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto
/gate/random/verbose 2

#-----------------------------------------------------------------------#
#          S T A R T   S I M U L A T I O N                              #
#-----------------------------------------------------------------------#
/gate/application/setTotalNumberOfPrimaries 2e7
/gate/application/start
