#=====================================================
# Lu177 betaminus emission spectrum: histogram, continuous energy spectrum
#=====================================================
/gate/source/addSource                  Lu177beta  gps
/gate/source/Lu177beta/attachTo         my_phantom
/gate/source/Lu177beta/gps/particle     e-
/gate/source/Lu177beta/gps/angtype	iso
/gate/source/Lu177beta/gps/energytype   Arb
/gate/source/Lu177beta/setIntensity     1
/gate/source/Lu177beta/gps/histname     arb
/gate/source/Lu177beta/gps/position     -0.00605 -0.00605 -0.00605 mm
/gate/source/Lu177beta/gps/type         Point

/gate/source/Lu177beta/gps/histpoint    0        5.707
/gate/source/Lu177beta/gps/histpoint    0.0001   5.705
/gate/source/Lu177beta/gps/histpoint    0.00011  5.704
/gate/source/Lu177beta/gps/histpoint    0.00012  5.704
/gate/source/Lu177beta/gps/histpoint    0.00013  5.704
/gate/source/Lu177beta/gps/histpoint    0.00014  5.704
/gate/source/Lu177beta/gps/histpoint    0.00015  5.703
/gate/source/Lu177beta/gps/histpoint    0.00016  5.703
/gate/source/Lu177beta/gps/histpoint    0.00018  5.703
/gate/source/Lu177beta/gps/histpoint    0.0002   5.702
/gate/source/Lu177beta/gps/histpoint    0.00022  5.702
/gate/source/Lu177beta/gps/histpoint    0.00024  5.701
/gate/source/Lu177beta/gps/histpoint    0.00026  5.701
/gate/source/Lu177beta/gps/histpoint    0.00028  5.7
/gate/source/Lu177beta/gps/histpoint    0.0003   5.7
/gate/source/Lu177beta/gps/histpoint    0.00032  5.699
/gate/source/Lu177beta/gps/histpoint    0.00036  5.698
/gate/source/Lu177beta/gps/histpoint    0.0004   5.697
/gate/source/Lu177beta/gps/histpoint    0.00045  5.696
/gate/source/Lu177beta/gps/histpoint    0.0005   5.694
/gate/source/Lu177beta/gps/histpoint    0.00055  5.693
/gate/source/Lu177beta/gps/histpoint    0.0006   5.692
/gate/source/Lu177beta/gps/histpoint    0.00065  5.691
/gate/source/Lu177beta/gps/histpoint    0.0007   5.689
/gate/source/Lu177beta/gps/histpoint    0.00075  5.688
/gate/source/Lu177beta/gps/histpoint    0.0008   5.687
/gate/source/Lu177beta/gps/histpoint    0.00085  5.685
/gate/source/Lu177beta/gps/histpoint    0.0009   5.684
/gate/source/Lu177beta/gps/histpoint    0.001    5.682
/gate/source/Lu177beta/gps/histpoint    0.0011   5.679
/gate/source/Lu177beta/gps/histpoint    0.0012   5.676
/gate/source/Lu177beta/gps/histpoint    0.0013   5.674
/gate/source/Lu177beta/gps/histpoint    0.0014   5.671
/gate/source/Lu177beta/gps/histpoint    0.0015   5.669
/gate/source/Lu177beta/gps/histpoint    0.0016   5.666
/gate/source/Lu177beta/gps/histpoint    0.0018   5.661
/gate/source/Lu177beta/gps/histpoint    0.002    5.656
/gate/source/Lu177beta/gps/histpoint    0.0022   5.651
/gate/source/Lu177beta/gps/histpoint    0.0024   5.646
/gate/source/Lu177beta/gps/histpoint    0.0026   5.641
/gate/source/Lu177beta/gps/histpoint    0.0028   5.636
/gate/source/Lu177beta/gps/histpoint    0.003    5.63
/gate/source/Lu177beta/gps/histpoint    0.0032   5.625
/gate/source/Lu177beta/gps/histpoint    0.0036   5.615
/gate/source/Lu177beta/gps/histpoint    0.004    5.605
/gate/source/Lu177beta/gps/histpoint    0.0045   5.592
/gate/source/Lu177beta/gps/histpoint    0.005    5.579
/gate/source/Lu177beta/gps/histpoint    0.0055   5.566
/gate/source/Lu177beta/gps/histpoint    0.006    5.554
/gate/source/Lu177beta/gps/histpoint    0.0065   5.541
/gate/source/Lu177beta/gps/histpoint    0.007    5.528
/gate/source/Lu177beta/gps/histpoint    0.0075   5.515
/gate/source/Lu177beta/gps/histpoint    0.008    5.503
/gate/source/Lu177beta/gps/histpoint    0.0085   5.49
/gate/source/Lu177beta/gps/histpoint    0.009    5.477
/gate/source/Lu177beta/gps/histpoint    0.01     5.452
/gate/source/Lu177beta/gps/histpoint    0.011    5.426
/gate/source/Lu177beta/gps/histpoint    0.012    5.401
/gate/source/Lu177beta/gps/histpoint    0.013    5.375
/gate/source/Lu177beta/gps/histpoint    0.014    5.357
/gate/source/Lu177beta/gps/histpoint    0.015    5.338
/gate/source/Lu177beta/gps/histpoint    0.016    5.319
/gate/source/Lu177beta/gps/histpoint    0.018    5.28
/gate/source/Lu177beta/gps/histpoint    0.02     5.24
/gate/source/Lu177beta/gps/histpoint    0.022    5.201
/gate/source/Lu177beta/gps/histpoint    0.024    5.161
/gate/source/Lu177beta/gps/histpoint    0.026    5.122
/gate/source/Lu177beta/gps/histpoint    0.028    5.082                   
/gate/source/Lu177beta/gps/histpoint    0.03     5.042
/gate/source/Lu177beta/gps/histpoint    0.032    5.002
/gate/source/Lu177beta/gps/histpoint    0.036    4.922
/gate/source/Lu177beta/gps/histpoint    0.04     4.841
/gate/source/Lu177beta/gps/histpoint    0.045    4.739
/gate/source/Lu177beta/gps/histpoint    0.05     4.638
/gate/source/Lu177beta/gps/histpoint    0.055    4.536
/gate/source/Lu177beta/gps/histpoint    0.06     4.434
/gate/source/Lu177beta/gps/histpoint    0.065    4.333
/gate/source/Lu177beta/gps/histpoint    0.07     4.232
/gate/source/Lu177beta/gps/histpoint    0.075    4.131
/gate/source/Lu177beta/gps/histpoint    0.08     4.031
/gate/source/Lu177beta/gps/histpoint    0.085    3.932                                              
/gate/source/Lu177beta/gps/histpoint    0.09     3.834
/gate/source/Lu177beta/gps/histpoint    0.1	 3.642
/gate/source/Lu177beta/gps/histpoint    0.11     3.456
/gate/source/Lu177beta/gps/histpoint    0.12     3.276
/gate/source/Lu177beta/gps/histpoint    0.13     3.106
/gate/source/Lu177beta/gps/histpoint    0.14     2.946
/gate/source/Lu177beta/gps/histpoint    0.15     2.797
/gate/source/Lu177beta/gps/histpoint    0.16     2.661
/gate/source/Lu177beta/gps/histpoint    0.18     2.433
/gate/source/Lu177beta/gps/histpoint    0.2	 2.223
/gate/source/Lu177beta/gps/histpoint    0.22     2.009
/gate/source/Lu177beta/gps/histpoint    0.24     1.793
/gate/source/Lu177beta/gps/histpoint    0.26     1.578
/gate/source/Lu177beta/gps/histpoint    0.28     1.367
/gate/source/Lu177beta/gps/histpoint    0.3	 1.161
/gate/source/Lu177beta/gps/histpoint    0.32     0.9643
/gate/source/Lu177beta/gps/histpoint    0.36     0.6102
/gate/source/Lu177beta/gps/histpoint    0.4	 0.3285
/gate/source/Lu177beta/gps/histpoint    0.45     0.08584
/gate/source/Lu177beta/gps/histpoint    0.4978   0    
/gate/source/Lu177beta/gps/arbint	Spline

#=====================================================
# monoenergetic photon emissions;  gammas
#=====================================================
/gate/source/addSource                  mono_ph gps
/gate/source/mono_ph/attachTo           my_phantom
/gate/source/mono_ph/gps/particle	gamma
/gate/source/mono_ph/gps/angtype        iso
/gate/source/mono_ph/gps/energytype     User
/gate/source/mono_ph/setIntensity	1.5543
/gate/source/mono_ph/gps/histname	energy
/gate/source/mono_ph/gps/position      -0.00605 -0.00605 -0.00605 mm
/gate/source/mono_ph/gps/type           Point

/gate/source/mono_ph/gps/histpoint	0.071646        0
/gate/source/mono_ph/gps/histpoint	0.071646        0.00154
/gate/source/mono_ph/gps/histpoint	0.071646        0
/gate/source/mono_ph/gps/histpoint	0.11295         0
/gate/source/mono_ph/gps/histpoint	0.11295         0.064
/gate/source/mono_ph/gps/histpoint	0.11295         0
/gate/source/mono_ph/gps/histpoint	0.136725        0
/gate/source/mono_ph/gps/histpoint	0.136725        0.00048
/gate/source/mono_ph/gps/histpoint	0.136725        0
/gate/source/mono_ph/gps/histpoint	0.208366        0
/gate/source/mono_ph/gps/histpoint	0.208366        0.11
/gate/source/mono_ph/gps/histpoint	0.208366        0
/gate/source/mono_ph/gps/histpoint	0.249674        0
/gate/source/mono_ph/gps/histpoint	0.249674        0.00212
/gate/source/mono_ph/gps/histpoint	0.249674        0
/gate/source/mono_ph/gps/histpoint	0.321316        0
/gate/source/mono_ph/gps/histpoint	0.321316        0.00219
/gate/source/mono_ph/gps/histpoint	0.321316        0

