# GATE Monte Carlo dose estimation using beta spectrum of  Sm-153 in spherical blood phantom #

#---------------------------------------------------------------------#
#                 V E R B O S I T Y                                   #
#---------------------------------------------------------------------#
/gate/verbose Physic    0
/gate/verbose Cuts	0
/gate/verbose SD        0
/gate/verbose Actions   0
/gate/verbose Actor     0
/gate/verbose Step	0
/gate/verbose Error     0
/gate/verbose Warning   0
/gate/verbose Output    0
/gate/verbose Beam	0
/gate/verbose Volume    0
/gate/verbose Image     0
/gate/verbose Geometry  0
/gate/verbose Core	0

/run/verbose 2
/event/verbose 2
/tracking/verbose 2

/gate/geometry/setMaterialDatabase /Users/atiwr/gate_data_files/GateMaterials.db
#----------------------------------------------------------------------#
#                           W O R L D                                  #
#----------------------------------------------------------------------#
/gate/world/geometry/setXLength         5 cm
/gate/world/geometry/setYLength         5 cm
/gate/world/geometry/setZLength         5 cm
/gate/world/setMaterial                 Water

#----------------------------------------------------------------------#
#            P H A N T O M         G E O M E T R Y                     #
#----------------------------------------------------------------------#
/gate/world/daughters/name              my_phantom
/gate/world/daughters/insert            sphere
/gate/my_phantom/setMaterial            Blood

/gate/my_phantom/geometry/setRmax	5.125 mm
/gate/my_phantom/geometry/setRmin	0.0 mm
/gate/my_phantom/vis/forceSolid
/gate/my_phantom/vis/setColor           grey
/gate/my_phantom/placement/setTranslation 0 0 0 mm

/gate/my_phantom/attachPhantomSD
# sphere radius = dosel size * # of concentric shells

#----------------------------------------------------------------------#
#                   A C T O R S                                        #
#----------------------------------------------------------------------#
/gate/actor/addActor          DoseActor    dosimetry
/gate/actor/dosimetry/attachTo             my_phantom
/gate/actor/dosimetry/stepHitType          random

#/gate/actor/dosimetry/setResolution	   500 500 500 
/gate/actor/dosimetry/setPosition          0 0 0 mm
/gate/actor/dosimetry/setSize              10.25 10.25 10.25 mm
/gate/actor/dosimetry/setVoxelSize         0.0205 0.0205 0.0205 mm

/gate/actor/dosimetry/enableDose            false
/gate/actor/dosimetry/enableEdep            true
/gate/actor/dosimetry/enableUncertaintyEdep true
/gate/actor/dosimetry/enableSquaredEdep     true
/gate/actor/dosimetry/save                  output/2e7_Sm153_blood.mhd
/gate/actor/dosimetry/saveEveryNSeconds     300

/gate/actor/addActor                        SimulationStatisticActor stat
/gate/actor/stat/save                       output/2e7_Sm153_blood_stats.txt
/gate/actor/stat/saveEveryNSeconds          300

#----------------------------------------------------------------------#
#             P H Y S I C S   D E S C R I P T I O N                    #
#----------------------------------------------------------------------#
/gate/physics/addPhysicsList  emstandard_opt3
/gate/physics/addProcess RayleighScattering
/gate/physics/processes/RayleighScattering/setModel PenelopeModel

# ---------------------------------------------------------------------#
#       E L E C T R O M A G N E T I C    O P T I O N S                 #
#----------------------------------------------------------------------#
/gate/physics/setEMin 0.1 keV
/gate/physics/setEMax 10 GeV
/gate/physics/setDEDXBinning   220
/gate/physics/setLambdaBinning 220

/gate/physics/Gamma/SetCutInRegion	world 0.1 mm
/gate/physics/Electron/SetCutInRegion   world 0.005 mm

/gate/physics/Gamma/SetCutInRegion	my_phantom 0.1 mm
/gate/physics/Electron/SetCutInRegion   my_phantom 0.005 mm

/gate/physics/SetMaxStepSizeInRegion    my_phantom 0.008812 mm
/gate/physics/ActivateStepLimiter e-
/gate/physics/processes/ElectronIonisation/setStepFunction e- 0.0001  0.001 mm

#----------------------------------------------------------------------#
#                     I N I T I A L I Z E                              #
#----------------------------------------------------------------------#
/gate/run/initialize
/gate/physics/displayCuts
/gate/physics/processList Enabled
/gate/physics/processList Initialized

#----------------------------------------------------------------------#
#           Beta spectrum : Discrete spectrum                          #
#----------------------------------------------------------------------#
/gate/source/addSource Sm153spectrum            gps
/gate/source/Sm153spectrum/attachTo             my_phantom
/gate/source/Sm153spectrum/gps/particle         e-

/gate/source/Sm153spectrum/gps/angtype          iso
/gate/source/Sm153spectrum/gps/energytype	Arb
/gate/source/Sm153spectrum/setIntensity         1
/gate/source/Sm153spectrum/gps/histname         arb
/gate/source/Sm153spectrum/gps/position         0 0 0 mm
/gate/source/Sm153spectrum/gps/type             Point

# first column is energy in MeV and second is intensity
# Refrence: doseinfo-radar.com/BetaSpec.zip

################################## Energy(MeV) ##### Intensity #
/gate/source/Sm153spectrum/gps/hist/point 0             0.0
/gate/source/Sm153spectrum/gps/hist/point 0.0408        1.03E-01
/gate/source/Sm153spectrum/gps/hist/point 0.0817        1.03E-01
/gate/source/Sm153spectrum/gps/hist/point 0.1225        1.01E-01
/gate/source/Sm153spectrum/gps/hist/point 0.1634        9.76E-02
/gate/source/Sm153spectrum/gps/hist/point 0.2042        9.32E-02
/gate/source/Sm153spectrum/gps/hist/point 0.2451        8.74E-02
/gate/source/Sm153spectrum/gps/hist/point 0.2859        8.04E-02
/gate/source/Sm153spectrum/gps/hist/point 0.3266        7.24E-02
/gate/source/Sm153spectrum/gps/hist/point 0.3676        6.35E-02
/gate/source/Sm153spectrum/gps/hist/point 0.4085        5.41E-02
/gate/source/Sm153spectrum/gps/hist/point 0.4493        4.44E-02
/gate/source/Sm153spectrum/gps/hist/point 0.4902        3.49E-02
/gate/source/Sm153spectrum/gps/hist/point 0.5311        2.58E-02
/gate/source/Sm153spectrum/gps/hist/point 0.5719        1.77E-02
/gate/source/Sm153spectrum/gps/hist/point 0.6127        1.09E-02
/gate/source/Sm153spectrum/gps/hist/point 0.6536        6.02E-03
/gate/source/Sm153spectrum/gps/hist/point 0.6945        2.92E-03
/gate/source/Sm153spectrum/gps/hist/point 0.7353        1.27E-03
/gate/source/Sm153spectrum/gps/hist/point 0.7761        4.86E-04
/gate/source/Sm153spectrum/gps/hist/point 0.8170        7.24E-05
/gate/source/Sm153spectrum/gps/arbint Lin     # Spline

/gate/source/list

#----------------------------------------------------------------------#
#               V I S U A L I S A T I O N                              #
#----------------------------------------------------------------------#
/vis/disable

/vis/open OGLSQt
/vis/viewer/reset
/vis/viewer/set/viewpointThetaPhi 30 60
/vis/viewer/zoom
/vis/viewer/set/style wireframe
/vis/drawVolume
/vis/viewer/flush
/vis/scene/add/trajectories
/tracking/storeTrajectory 1
/vis/scene/add/hits
/vis/scene/endOfEventAction accumulate 10

#-----------------------------------------------------------------------#
#          R A N D O M     G E N E R A T O R                            #
#-----------------------------------------------------------------------#
/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto
/gate/random/verbose 2

#-----------------------------------------------------------------------#
#          S T A R T   S I M U L A T I O N                              #
#-----------------------------------------------------------------------#
/gate/application/setTotalNumberOfPrimaries 2e7
/gate/application/start


