# Y90 decay spectrum
# Taken from MIRD radionuclide data and decay schemes, 2nd edition, KF Eckerman & A Endo Eds, 2008

#=====================================================
# betaminus emission spectrum: histogram, continuous energy spectrum
#=====================================================
/gate/source/addSource 			Y90Source    gps
/gate/source/Y90Source/gps/centre	-0.1659 -0.1659 -0.1659 mm
/gate/source/Y90Source/gps/particle 	e-

/gate/source/Y90Source/gps/angtype	iso
/gate/source/Y90Source/gps/energytype 	Arb
/gate/source/Y90Source/setIntensity     1
/gate/source/Y90Source/gps/histname 	arb
/gate/source/Y90Source/gps/type 	Point

#/gate/source/Y90Source/gps/emin 	0. keV
#/gate/source/Y90Source/gps/emax 	2284. keV

# activity is not needed if we use setinstensity when using several sources
# Warning : probability density (or point wise) and not bin values
/gate/source/Y90Source/gps/histpoint	0		0.3379    
/gate/source/Y90Source/gps/histpoint    0.0001		0.3379
/gate/source/Y90Source/gps/histpoint    0.00011		0.3379
/gate/source/Y90Source/gps/histpoint    0.00012		0.3379
/gate/source/Y90Source/gps/histpoint    0.00013		0.3379
/gate/source/Y90Source/gps/histpoint    0.00014		0.3379
/gate/source/Y90Source/gps/histpoint    0.00015		0.3379
/gate/source/Y90Source/gps/histpoint    0.00016		0.3379
/gate/source/Y90Source/gps/histpoint	0.00018		0.3379
/gate/source/Y90Source/gps/histpoint	0.0002		0.338
/gate/source/Y90Source/gps/histpoint	0.00022		0.338
/gate/source/Y90Source/gps/histpoint	0.00024		0.338
/gate/source/Y90Source/gps/histpoint	0.00026		0.338
/gate/source/Y90Source/gps/histpoint	0.00028		0.338
/gate/source/Y90Source/gps/histpoint	0.0003		0.338
/gate/source/Y90Source/gps/histpoint	0.00032		0.338
/gate/source/Y90Source/gps/histpoint	0.00036		0.338
/gate/source/Y90Source/gps/histpoint	0.0004		0.338
/gate/source/Y90Source/gps/histpoint	0.00045		0.338
/gate/source/Y90Source/gps/histpoint	0.0005		0.338
/gate/source/Y90Source/gps/histpoint	0.00055		0.338
/gate/source/Y90Source/gps/histpoint	0.0006		0.338
/gate/source/Y90Source/gps/histpoint	0.00065		0.338
/gate/source/Y90Source/gps/histpoint	0.0007		0.338
/gate/source/Y90Source/gps/histpoint	0.00075		0.338
/gate/source/Y90Source/gps/histpoint	0.0008		0.338
/gate/source/Y90Source/gps/histpoint	0.00085		0.338
/gate/source/Y90Source/gps/histpoint	0.0009		0.338
/gate/source/Y90Source/gps/histpoint	0.001		0.338
/gate/source/Y90Source/gps/histpoint	0.0011		0.338
/gate/source/Y90Source/gps/histpoint	0.0012		0.338
/gate/source/Y90Source/gps/histpoint	0.0013		0.338
/gate/source/Y90Source/gps/histpoint	0.0014		0.338
/gate/source/Y90Source/gps/histpoint	0.0015		0.338
/gate/source/Y90Source/gps/histpoint	0.0016		0.3381
/gate/source/Y90Source/gps/histpoint	0.0018		0.3381
/gate/source/Y90Source/gps/histpoint	0.002		0.3381
/gate/source/Y90Source/gps/histpoint	0.0022		0.3381
/gate/source/Y90Source/gps/histpoint	0.0024		0.3381
/gate/source/Y90Source/gps/histpoint	0.0026		0.3381
/gate/source/Y90Source/gps/histpoint	0.0028		0.3381
/gate/source/Y90Source/gps/histpoint	0.003		0.3382
/gate/source/Y90Source/gps/histpoint	0.0032		0.3382
/gate/source/Y90Source/gps/histpoint	0.0036		0.3382
/gate/source/Y90Source/gps/histpoint	0.0042		0.3382
/gate/source/Y90Source/gps/histpoint	0.0045		0.3383
/gate/source/Y90Source/gps/histpoint	0.005		0.3383
/gate/source/Y90Source/gps/histpoint	0.0055		0.3383
/gate/source/Y90Source/gps/histpoint	0.006		0.3385
/gate/source/Y90Source/gps/histpoint	0.0065		0.3885
/gate/source/Y90Source/gps/histpoint	0.007		0.3391
/gate/source/Y90Source/gps/histpoint	0.0075		0.3394
/gate/source/Y90Source/gps/histpoint	0.008		0.3398
/gate/source/Y90Source/gps/histpoint	0.0085		0.3401
/gate/source/Y90Source/gps/histpoint	0.009		0.3404
/gate/source/Y90Source/gps/histpoint	0.01		0.341
/gate/source/Y90Source/gps/histpoint	0.011		0.3416
/gate/source/Y90Source/gps/histpoint	0.012		0.3422
/gate/source/Y90Source/gps/histpoint	0.013		0.3428
/gate/source/Y90Source/gps/histpoint	0.014		0.3435
/gate/source/Y90Source/gps/histpoint	0.015		0.3441
/gate/source/Y90Source/gps/histpoint	0.016		0.3447
/gate/source/Y90Source/gps/histpoint	0.018		0.3459
/gate/source/Y90Source/gps/histpoint	0.02		0.3472
/gate/source/Y90Source/gps/histpoint	0.022		0.3484
/gate/source/Y90Source/gps/histpoint	0.024		0.3497
/gate/source/Y90Source/gps/histpoint	0.026		0.351
/gate/source/Y90Source/gps/histpoint	0.028		0.3523
/gate/source/Y90Source/gps/histpoint	0.03		0.3536
/gate/source/Y90Source/gps/histpoint	0.032		0.355
/gate/source/Y90Source/gps/histpoint	0.036		0.3577
/gate/source/Y90Source/gps/histpoint	0.04		0.3605
/gate/source/Y90Source/gps/histpoint	0.045		0.3641
/gate/source/Y90Source/gps/histpoint	0.05		0.3677
/gate/source/Y90Source/gps/histpoint	0.055		0.3713
/gate/source/Y90Source/gps/histpoint	0.06		0.375
/gate/source/Y90Source/gps/histpoint	0.065		0.3788
/gate/source/Y90Source/gps/histpoint	0.07		0.3825
/gate/source/Y90Source/gps/histpoint	0.075		0.3863
/gate/source/Y90Source/gps/histpoint	0.08		0.39
/gate/source/Y90Source/gps/histpoint	0.085		0.3938
/gate/source/Y90Source/gps/histpoint	0.09		0.3975
/gate/source/Y90Source/gps/histpoint	0.1		0.405
/gate/source/Y90Source/gps/histpoint	0.11		0.4124
/gate/source/Y90Source/gps/histpoint	0.12		0.4197
/gate/source/Y90Source/gps/histpoint	0.13		0.4269
/gate/source/Y90Source/gps/histpoint	0.14		0.434
/gate/source/Y90Source/gps/histpoint	0.15		0.441
/gate/source/Y90Source/gps/histpoint	0.16		0.4479
/gate/source/Y90Source/gps/histpoint	0.18		0.4612
/gate/source/Y90Source/gps/histpoint	0.2		0.474
/gate/source/Y90Source/gps/histpoint	0.22		0.4862
/gate/source/Y90Source/gps/histpoint	0.24		0.4978
/gate/source/Y90Source/gps/histpoint	0.26		0.5089
/gate/source/Y90Source/gps/histpoint	0.28		0.5194
/gate/source/Y90Source/gps/histpoint	0.3		0.5294
/gate/source/Y90Source/gps/histpoint	0.32		0.5387
/gate/source/Y90Source/gps/histpoint	0.36		0.5559
/gate/source/Y90Source/gps/histpoint	0.4		0.5709
/gate/source/Y90Source/gps/histpoint	0.45		0.5868
/gate/source/Y90Source/gps/histpoint	0.5		0.5998
/gate/source/Y90Source/gps/histpoint	0.55		0.6102
/gate/source/Y90Source/gps/histpoint	0.6		0.6181
/gate/source/Y90Source/gps/histpoint	0.65		0.6238
/gate/source/Y90Source/gps/histpoint	0.7		0.6274
/gate/source/Y90Source/gps/histpoint	0.75		0.6292
/gate/source/Y90Source/gps/histpoint	0.8		0.6292
/gate/source/Y90Source/gps/histpoint	0.85		0.6276
/gate/source/Y90Source/gps/histpoint	0.9		0.6245
/gate/source/Y90Source/gps/histpoint	1		0.6141
/gate/source/Y90Source/gps/histpoint	1.1		0.5979
/gate/source/Y90Source/gps/histpoint	1.2		0.5756
/gate/source/Y90Source/gps/histpoint	1.3		0.5466
/gate/source/Y90Source/gps/histpoint	1.4		0.5099
/gate/source/Y90Source/gps/histpoint	1.5		0.4647
/gate/source/Y90Source/gps/histpoint	1.6		0.4105
/gate/source/Y90Source/gps/histpoint	1.8		0.2271
/gate/source/Y90Source/gps/histpoint	2		0.1276
/gate/source/Y90Source/gps/histpoint	2.2		0.01403
/gate/source/Y90Source/gps/histpoint	2.2801		0

/gate/source/Y90Source/gps/arbint               Spline

/gate/source/Y90Source/gps/confine		my_phantom_phys
#/gate/source/Y90Source/attachTo my_phantom
/gate/source/Y90Source/dump 1

#=====================================================
# monoenergetic photon emissions x-rays and gammas
#=====================================================
/gate/source/addSource 			mono_ph   gps 
/gate/source/mono_ph/gps/centre        -0.1659 -0.1659 -0.1659 mm
/gate/source/mono_ph/gps/particle 	gamma

/gate/source/mono_ph/gps/angtype 	iso
/gate/source/mono_ph/gps/energytype 	User
/gate/source/mono_ph/gps/histname 	energy
/gate/source/mono_ph/setIntensity  	0.001466014
/gate/source/mono_ph/gps/type           Point

# Warning : probability bin values
/gate/source/mono_ph/gps/histpoint 	6.524e-06		0
/gate/source/mono_ph/gps/histpoint  	6.524e-06	0.001388
/gate/source/mono_ph/gps/histpoint      6.524e-06		0
/gate/source/mono_ph/gps/histpoint	2.730e-05		0
/gate/source/mono_ph/gps/histpoint	2.370e-05	9.748e-10
/gate/source/mono_ph/gps/histpoint	2.370e-05       	0
/gate/source/mono_ph/gps/histpoint	8.740e-05		0
/gate/source/mono_ph/gps/histpoint	8.734e-05	1.308e-13
/gate/source/mono_ph/gps/histpoint	8.734e-05		0
/gate/source/mono_ph/gps/histpoint	1.802e-04		0
/gate/source/mono_ph/gps/histpoint	1.802e-04	6.127e-08
/gate/source/mono_ph/gps/histpoint	1.802e-04		0
/gate/source/mono_ph/gps/histpoint	2.024e-04		0
/gate/source/mono_ph/gps/histpoint	2.024e-04	3.187e-10
/gate/source/mono_ph/gps/histpoint	2.024e-04		0
/gate/source/mono_ph/gps/histpoint	2.898e-04		0
/gate/source/mono_ph/gps/histpoint	2.898e-04	1.991e-09
/gate/source/mono_ph/gps/histpoint	2.898e-04		0
/gate/source/mono_ph/gps/histpoint	1.803e-03		0
/gate/source/mono_ph/gps/histpoint	1.803e-03	3.801e-07
/gate/source/mono_ph/gps/histpoint	1.803e-03		0
/gate/source/mono_ph/gps/histpoint	1.880e-03		0
/gate/source/mono_ph/gps/histpoint	1.880e-03	1.523e-09
/gate/source/mono_ph/gps/histpoint	1.880e-03		0
/gate/source/mono_ph/gps/histpoint	1.890e-03		0
/gate/source/mono_ph/gps/histpoint	1.890e-03	1.105e-07
/gate/source/mono_ph/gps/histpoint	1.890e-03		0
/gate/source/mono_ph/gps/histpoint	1.894e-03		0
/gate/source/mono_ph/gps/histpoint	1.894e-03	1.440e-09
/gate/source/mono_ph/gps/histpoint	1.894e-03		0
/gate/source/mono_ph/gps/histpoint	1.981e-03		0
/gate/source/mono_ph/gps/histpoint	1.981e-03	9.811e-10
/gate/source/mono_ph/gps/histpoint	1.981e-03		0
/gate/source/mono_ph/gps/histpoint	2.032e-03		0
/gate/source/mono_ph/gps/histpoint	2.032e-03	2.303e-07
/gate/source/mono_ph/gps/histpoint	2.032e-03		0
/gate/source/mono_ph/gps/histpoint	2.043e-03		0
/gate/source/mono_ph/gps/histpoint	2.034e-03	2.096e-06
/gate/source/mono_ph/gps/histpoint	2.034e-03		0
/gate/source/mono_ph/gps/histpoint	2.119e-03		0
/gate/source/mono_ph/gps/histpoint	2.119e-03	9.704e-07
/gate/source/mono_ph/gps/histpoint	2.119e-03		0
/gate/source/mono_ph/gps/histpoint	2.165e-03		0
/gate/source/mono_ph/gps/histpoint	2.165e-03	1.740e-08
/gate/source/mono_ph/gps/histpoint	2.165e-03		0
/gate/source/mono_ph/gps/histpoint	2.170e-03		0
/gate/source/mono_ph/gps/histpoint	2.170e-03	3.704e-08
/gate/source/mono_ph/gps/histpoint	2.170e-03		0
/gate/source/mono_ph/gps/histpoint	2.184e-03		0
/gate/source/mono_ph/gps/histpoint	2.184e-03	6.447e-08
/gate/source/mono_ph/gps/histpoint	2.184e-03		0
/gate/source/mono_ph/gps/histpoint	2.186e-03		0
/gate/source/mono_ph/gps/histpoint	2.186e-03	3.958e-11
/gate/source/mono_ph/gps/histpoint	2.186e-03		0
/gate/source/mono_ph/gps/histpoint	2.100e-03		0
/gate/source/mono_ph/gps/histpoint	2.188e-03	3.795e-11
/gate/source/mono_ph/gps/histpoint	2.188e-03		0
/gate/source/mono_ph/gps/histpoint	2.218e-03		0
/gate/source/mono_ph/gps/histpoint	2.218e-03	2.869e-09
/gate/source/mono_ph/gps/histpoint	2.218e-03		0
/gate/source/mono_ph/gps/histpoint	2.219e-03		0
/gate/source/mono_ph/gps/histpoint	2.219e-03	2.541e-08
/gate/source/mono_ph/gps/histpoint	2.219e-03		0
/gate/source/mono_ph/gps/histpoint	2.252e-03		0
/gate/source/mono_ph/gps/histpoint	2.252e-03	7.589e-09
/gate/source/mono_ph/gps/histpoint	2.252e-03		0
/gate/source/mono_ph/gps/histpoint	2.275e-03		0
/gate/source/mono_ph/gps/histpoint	2.275e-03	3.293e-11
/gate/source/mono_ph/gps/histpoint	2.275e-03		0
/gate/source/mono_ph/gps/histpoint	2.306e-03		0
/gate/source/mono_ph/gps/histpoint	2.306e-03	1.219e-08
/gate/source/mono_ph/gps/histpoint	2.306e-03		0
/gate/source/mono_ph/gps/histpoint	2.322e-03		0
/gate/source/mono_ph/gps/histpoint	2.315e-03	2.842e-10
/gate/source/mono_ph/gps/histpoint	2.315e-03		0
/gate/source/mono_ph/gps/histpoint	2.324e-03		0
/gate/source/mono_ph/gps/histpoint	2.324e-03	4.322e-10
/gate/source/mono_ph/gps/histpoint	2.324e-03		0
/gate/source/mono_ph/gps/histpoint	2.476e-03		0
/gate/source/mono_ph/gps/histpoint	2.476e-03	5.359e-09
/gate/source/mono_ph/gps/histpoint	2.476e-03		0
/gate/source/mono_ph/gps/histpoint	2.478e-03		0
/gate/source/mono_ph/gps/histpoint	2.478e-03	9.412e-09
/gate/source/mono_ph/gps/histpoint	2.478e-03		0
/gate/source/mono_ph/gps/histpoint	2.508e-03		0
/gate/source/mono_ph/gps/histpoint	2.508e-03	3.139e-12
/gate/source/mono_ph/gps/histpoint	2.508e-03		0
/gate/source/mono_ph/gps/histpoint	1.574e-02		0
/gate/source/mono_ph/gps/histpoint	1.574e-02	4.125e-05
/gate/source/mono_ph/gps/histpoint	1.574e-02		0
/gate/source/mono_ph/gps/histpoint	1.762e-02		0
/gate/source/mono_ph/gps/histpoint	1.767e-02	3.253e-06
/gate/source/mono_ph/gps/histpoint	1.767e-02		0
/gate/source/mono_ph/gps/histpoint	1.763e-02		0
/gate/source/mono_ph/gps/histpoint	1.763e-02	6.334e-06
/gate/source/mono_ph/gps/histpoint	1.763e-02		0
/gate/source/mono_ph/gps/histpoint	1.777e-02		0
/gate/source/mono_ph/gps/histpoint	1.777e-02	1.356e-08
/gate/source/mono_ph/gps/histpoint	1.777e-02		0
/gate/source/mono_ph/gps/histpoint	1.778e-02		0
/gate/source/mono_ph/gps/histpoint	1.778e-02	1.926e-08
/gate/source/mono_ph/gps/histpoint	1.778e-02		0	
/gate/source/mono_ph/gps/histpoint	1.792e-02		0
/gate/source/mono_ph/gps/histpoint	1.792e-02	5.327e-07
/gate/source/mono_ph/gps/histpoint	1.792e-02		0
/gate/source/mono_ph/gps/histpoint	1.793e-02		0
/gate/source/mono_ph/gps/histpoint	1.793e-02	1.023e-06
/gate/source/mono_ph/gps/histpoint	1.793e-02		0
/gate/source/mono_ph/gps/histpoint	1.796e-02		0
/gate/source/mono_ph/gps/histpoint	1.796e-02	1.915e-10
/gate/source/mono_ph/gps/histpoint	1.796e-02		0
/gate/source/mono_ph/gps/histpoint	1.797e-02		0
/gate/source/mono_ph/gps/histpoint	1.797e-02	2.702e-10
/gate/source/mono_ph/gps/histpoint	1.797e-02		0
/gate/source/mono_ph/gps/histpoint	2.18624			0
/gate/source/mono_ph/gps/histpoint	2.18624		1.4e-08
/gate/source/mono_ph/gps/histpoint	2.18624			0

/gate/source/mono_ph/gps/confine              my_phantom_phys
/gate/source/mono_ph/dump 1

#=====================================================
# monoenergetic discrete electron emissions Auger and IC 
#=====================================================
/gate/source/addSource 			mono_el  gps
/gate/source/mono_el/gps/centre        -0.1659 -0.1659 -0.1659 mm
/gate/source/mono_el/gps/particle 	e-

/gate/source/mono_el/gps/angtype 	iso
/gate/source/mono_el/setIntensity 	0.000115
/gate/source/mono_el/gps/energytype 	User
/gate/source/mono_el/gps/histname 	energy
/gate/source/mono_el/gps/type           Point

# Warning : probability  bin values
/gate/source/mono_el/gps/histpoint	2.2236E-05		0
/gate/source/mono_el/gps/histpoint	2.2236E-05	7.3581E-04
/gate/source/mono_el/gps/histpoint	2.2236E-05		0
/gate/source/mono_el/gps/histpoint	9.8444E-15		0
/gate/source/mono_el/gps/histpoint	9.8444E-15	1.0999E-04
/gate/source/mono_el/gps/histpoint	9.8444E-05		0
/gate/source/mono_el/gps/histpoint	1.0613E-04		0
/gate/source/mono_el/gps/histpoint	1.0613E-04	2.2767E-05
/gate/source/mono_el/gps/histpoint	1.0613E-04		0
/gate/source/mono_el/gps/histpoint	1.1786E-04		0
/gate/source/mono_el/gps/histpoint	1.1786E-04	2.5211E-04
/gate/source/mono_el/gps/histpoint	1.1786E-04		0
/gate/source/mono_el/gps/histpoint	1.5812E-04		0
/gate/source/mono_el/gps/histpoint	1.5812E-04	7.4439E-02
/gate/source/mono_el/gps/histpoint	1.5812E-04		0
/gate/source/mono_el/gps/histpoint	1.7537E-03		0
/gate/source/mono_el/gps/histpoint	1.7537E-03	1.0477E-04
/gate/source/mono_el/gps/histpoint	1.7537E-03		0
/gate/source/mono_el/gps/histpoint	1.9445E-03		0
/gate/source/mono_el/gps/histpoint	1.9445E-03	1.1745E-05
/gate/source/mono_el/gps/histpoint	1.9448E-03		0
/gate/source/mono_el/gps/histpoint	2.1862E-03		0
/gate/source/mono_el/gps/histpoint	2.1862E-03	4.5931E-07
/gate/source/mono_el/gps/histpoint	2.1862E-03		0
/gate/source/mono_el/gps/histpoint	1.3327E-02		0
/gate/source/mono_el/gps/histpoint	1.3327E-02	2.0015E-05
/gate/source/mono_el/gps/histpoint	1.3327E-02		0
/gate/source/mono_el/gps/histpoint	1.5334E-02		0
/gate/source/mono_el/gps/histpoint	1.5334E-02	7.1283E-06
/gate/source/mono_el/gps/histpoint	1.5334E-02		0
/gate/source/mono_el/gps/histpoint	1.7343E-02		0
/gate/source/mono_el/gps/histpoint	1.7343E-02	6.0990E-07
/gate/source/mono_el/gps/histpoint	1.7343E-02		0
/gate/source/mono_el/gps/histpoint	1.74274			0
/gate/source/mono_el/gps/histpoint	1.74274		0.000101728
/gate/source/mono_el/gps/histpoint	1.74274			0
/gate/source/mono_el/gps/histpoint	1.75819			0
/gate/source/mono_el/gps/histpoint	1.75819		1.09929e-05
/gate/source/mono_el/gps/histpoint	1.75819			0
/gate/source/mono_el/gps/histpoint	1.76037			0
/gate/source/mono_el/gps/histpoint	1.76037		1.9427e-06
/gate/source/mono_el/gps/histpoint	1.76037			0
/gate/source/mono_el/gps/histpoint	1.76070			0
/gate/source/mono_el/gps/histpoint	1.76070		3.3647e-07
/gate/source/mono_el/gps/histpoint	1.76070			0
/gate/source/mono_el/gps/histpoint	2.16828			0
/gate/source/mono_el/gps/histpoint	2.16828		1.72e-12
/gate/source/mono_el/gps/histpoint	2.16828			0
/gate/source/mono_el/gps/histpoint	2.18373			0
/gate/source/mono_el/gps/histpoint	2.18373		1.8619e-13
/gate/source/mono_el/gps/histpoint	2.18373			0
/gate/source/mono_el/gps/histpoint	2.18373			0
/gate/source/mono_el/gps/histpoint	2.18373		2.067e-15
/gate/source/mono_el/gps/histpoint	2.18373			0
/gate/source/mono_el/gps/histpoint	2.18042			0
/gate/source/mono_el/gps/histpoint	2.18402		2.031e-15
/gate/source/mono_el/gps/histpoint	2.18402			0
/gate/source/mono_el/gps/histpoint	2.18591			0
/gate/source/mono_el/gps/histpoint	2.18591		3.3898e-14
/gate/source/mono_el/gps/histpoint	2.18591			0
/gate/source/mono_el/gps/histpoint	2.18624			0
/gate/source/mono_el/gps/histpoint	2.18624		5.6682e-15
/gate/source/mono_el/gps/histpoint	2.18624			0

/gate/source/mono_el/gps/confine              my_phantom_phys
/gate/source/mono_el/dump 1

/gate/source/list
