# GATE macros for the simulation of Y-90 beta emitter to calculate the absorbed dose:
#---------------------------------------------------------------------#
#                 V E R B O S I T Y                                   #
#---------------------------------------------------------------------#
/gate/verbose Physic    0
/gate/verbose Cuts      0
/gate/verbose SD        0
/gate/verbose Actions   0
/gate/verbose Actor     0
/gate/verbose Step      0
/gate/verbose Error     0
/gate/verbose Warning   0
/gate/verbose Output    0
/gate/verbose Beam      0
/gate/verbose Volume    0
/gate/verbose Image     0
/gate/verbose Geometry  0
/gate/verbose Core      0

/run/verbose 2
/event/verbose 2
/tracking/verbose 2

/gate/geometry/setMaterialDatabase /Users/atiwr/gate_data_files/GateMaterials.db
#----------------------------------------------------------------------#
#                           W O R L D                                  #
#----------------------------------------------------------------------#
/gate/world/geometry/setXLength         8.0 cm
/gate/world/geometry/setYLength         8.0 cm
/gate/world/geometry/setZLength         8.0 cm
/gate/world/setMaterial         Water

#----------------------------------------------------------------------#
#                  P H A N T O M   G E O M E T R Y                     #
#----------------------------------------------------------------------#
/gate/world/daughters/name                 my_phantom
/gate/world/daughters/insert               sphere
/gate/my_phantom/setMaterial               Water

/gate/my_phantom/placement/setTranslation  -0.0553 -0.0553 -0.0553 mm
/gate/my_phantom/geometry/setRmax          22.1753 mm
/gate/my_phantom/geometry/setRmin          0. mm
/gate/my_phantom/vis/forceSolid
/gate/my_phantom/vis/setColor               grey
/gate/my_phantom/attachPhantomSD

#----------------------------------------------------------------------#
#               A C T O R S                                            #
#----------------------------------------------------------------------#
/gate/actor/addActor            DoseActor       dosimetry
/gate/actor/dosimetry/attachTo                  my_phantom
/gate/actor/dosimetry/stepHitType           	random            

/gate/actor/dosimetry/setVoxelSize         	0.1106 0.1106 0.1106  mm
#/gate/actor/dosimetry/setResolution            401 401 401
/gate/actor/dosimetry/setSize                   44.3506 44.3506 44.3506 mm
/gate/actor/dosimetry/setPosition           	-0.0553 -0.0553 -0.0553 mm

/gate/actor/dosimetry/enableDose            	false
/gate/actor/dosimetry/enableEdep            	true
/gate/actor/dosimetry/enableUncertaintyEdep 	true
/gate/actor/dosimetry/enableSquaredEdep         true
/gate/actor/dosimetry/save                      output/2e7_Y90_water.mhd
/gate/actor/dosimetry/saveEveryNSeconds         120

/gate/actor/addActor                            SimulationStatisticActor stat
/gate/actor/stat/save                           output/2e7_Y90_water.txt
/gate/actor/stat/saveEveryNSeconds              120

#----------------------------------------------------------------------#
#             P H Y S I C S   D E S C R I P T I O N                    #
#----------------------------------------------------------------------#
/gate/physics/addPhysicsList  emstandard_opt3

/gate/physics/addProcess RayleighScattering
/gate/physics/processes/RayleighScattering/setModel PenelopeModel

/gate/physics/addProcess GammaConversion
/gate/physics/processes/GammaConversion/setModel StandardModel

# ---------------------------------------------------------------------#
#                 ELECTROMAGNETIC OPTIONS                              #
#----------------------------------------------------------------------#
/gate/physics/setEMin 0.1 keV
/gate/physics/setEMax 10 GeV
/gate/physics/setDEDXBinning   220
/gate/physics/setLambdaBinning 220

/gate/physics/Gamma/SetCutInRegion      world 0.5 mm    # 1 keV	energy cut in water
/gate/physics/Electron/SetCutInRegion   world 0.005 mm  #  keV energy cut in water
/gate/physics/Positron/SetCutInRegion   world 0.005 mm

/gate/physics/Gamma/SetCutInRegion      my_phantom 0.1 mm      # 1 keV energy cut in water
/gate/physics/Electron/SetCutInRegion   my_phantom 0.004 mm    #  keV energy cut in water
/gate/physics/Positron/SetCutInRegion   my_phantom 0.004 mm
#/gate/physics/ActivateSpecialCuts e-
#/gate/physics/ActivateSpecialCuts gamma

/gate/physics/SetMaxStepSizeInRegion    my_phantom 0.1106 mm
/gate/physics/ActivateStepLimiter e-
/gate/physics/ActivateStepLimiter gamma

/gate/physics/processes/ElectronIonisation/setStepFunction e- 0.0001  0.001 mm
/gate/physics/processes/ElectronIonisation/setStepFunction e+ 0.0001  0.001 mm

/gate/physics/processes/eMultipleScattering/setGeometricalStepLimiterType e- distanceToBoundary
/gate/physics/processes/eMultipleScattering/setGeometricalStepLimiterType e+ distanceToBoundary

#----------------------------------------------------------------------#
#                     I N I T I A L I Z E                              #
#----------------------------------------------------------------------#
/gate/run/initialize
/gate/physics/displayCuts
/gate/physics/processList Enabled
/gate/physics/processList Initialized

#----------------------------------------------------------------------#
#        Y-90  beta minus source                                       #
#----------------------------------------------------------------------#
/control/execute sources_Y90_Histo.mac
#/control/execute new_source_file.mac

/gate/source/list
/gate/output/verbose 2

#----------------------------------------------------------------------#
#               V I S U A L I S A T I O N                              #
#----------------------------------------------------------------------#
#/vis/disable
/vis/open OGLSQt
/vis/viewer/reset
/vis/viewer/set/viewpointThetaPhi 30 60
/vis/viewer/zoom 5
/vis/viewer/set/style wireframe
/vis/drawVolume
/vis/viewer/flush
/vis/scene/add/trajectories
/tracking/storeTrajectory 1

#-----------------------------------------------------------------------#
#          R A N D O M     G E N E R A T O R                            #
#-----------------------------------------------------------------------#
/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto
/gate/random/verbose 2

#-----------------------------------------------------------------------#
#          S T A R T   S I M U L A T I O N                              #
#-----------------------------------------------------------------------#
/gate/application/setTotalNumberOfPrimaries 2e7
/gate/application/start
