# Y90 decay spectrum
# Taken from MIRD radionuclide data and decay schemes, 2nd edition, KF Eckerman & A Endo Eds, 2008

#=====================================================
# betaminus emission spectrum: histogram, continuous energy spectrum
#=====================================================
/gate/source/addSource 			Y90Source    gps
/gate/source/Y90Source/gps/centre	-0.0553 -0.0553 -0.0553 mm
/gate/source/Y90Source/gps/particle 	e-

/gate/source/Y90Source/gps/angtype	iso
/gate/source/Y90Source/gps/energytype 	Arb
/gate/source/Y90Source/setIntensity     1
/gate/source/Y90Source/gps/histname 	arb
/gate/source/Y90Source/gps/type 	Point

#/gate/source/Y90Source/gps/emin 	0. keV
#/gate/source/Y90Source/gps/emax 	2284. keV

# activity is not needed if we use setinstensity when using several sources
# Warning : probability density (or point wise) and not bin values
/gate/source/Y90Source/gps/histpoint	0		0.3379    
/gate/source/Y90Source/gps/histpoint    0.0001		0.3379
/gate/source/Y90Source/gps/histpoint    0.00011		0.3379
/gate/source/Y90Source/gps/histpoint    0.00012		0.3379
/gate/source/Y90Source/gps/histpoint    0.00013		0.3379
/gate/source/Y90Source/gps/histpoint    0.00014		0.3379
/gate/source/Y90Source/gps/histpoint    0.00015		0.3379
/gate/source/Y90Source/gps/histpoint    0.00016		0.3379
/gate/source/Y90Source/gps/histpoint	0.00018		0.3379
/gate/source/Y90Source/gps/histpoint	0.0002		0.338
/gate/source/Y90Source/gps/histpoint	0.00022		0.338
/gate/source/Y90Source/gps/histpoint	0.00024		0.338
/gate/source/Y90Source/gps/histpoint	0.00026		0.338
/gate/source/Y90Source/gps/histpoint	0.00028		0.338
/gate/source/Y90Source/gps/histpoint	0.0003		0.338
/gate/source/Y90Source/gps/histpoint	0.00032		0.338
/gate/source/Y90Source/gps/histpoint	0.00036		0.338
/gate/source/Y90Source/gps/histpoint	0.0004		0.338
/gate/source/Y90Source/gps/histpoint	0.00045		0.338
/gate/source/Y90Source/gps/histpoint	0.0005		0.338
/gate/source/Y90Source/gps/histpoint	0.00055		0.338
/gate/source/Y90Source/gps/histpoint	0.0006		0.338
/gate/source/Y90Source/gps/histpoint	0.00065		0.338
/gate/source/Y90Source/gps/histpoint	0.0007		0.338
/gate/source/Y90Source/gps/histpoint	0.00075		0.338
/gate/source/Y90Source/gps/histpoint	0.0008		0.338
/gate/source/Y90Source/gps/histpoint	0.00085		0.338
/gate/source/Y90Source/gps/histpoint	0.0009		0.338
/gate/source/Y90Source/gps/histpoint	0.001		0.338
/gate/source/Y90Source/gps/histpoint	0.0011		0.338
/gate/source/Y90Source/gps/histpoint	0.0012		0.338
/gate/source/Y90Source/gps/histpoint	0.0013		0.338
/gate/source/Y90Source/gps/histpoint	0.0014		0.338
/gate/source/Y90Source/gps/histpoint	0.0015		0.338
/gate/source/Y90Source/gps/histpoint	0.0016		0.3381
/gate/source/Y90Source/gps/histpoint	0.0018		0.3381
/gate/source/Y90Source/gps/histpoint	0.002		0.3381
/gate/source/Y90Source/gps/histpoint	0.0022		0.3381
/gate/source/Y90Source/gps/histpoint	0.0024		0.3381
/gate/source/Y90Source/gps/histpoint	0.0026		0.3381
/gate/source/Y90Source/gps/histpoint	0.0028		0.3381
/gate/source/Y90Source/gps/histpoint	0.003		0.3382
/gate/source/Y90Source/gps/histpoint	0.0032		0.3382
/gate/source/Y90Source/gps/histpoint	0.0036		0.3382
/gate/source/Y90Source/gps/histpoint	0.0042		0.3382
/gate/source/Y90Source/gps/histpoint	0.0045		0.3383
/gate/source/Y90Source/gps/histpoint	0.005		0.3383
/gate/source/Y90Source/gps/histpoint	0.0055		0.3383
/gate/source/Y90Source/gps/histpoint	0.006		0.3385
/gate/source/Y90Source/gps/histpoint	0.0065		0.3885
/gate/source/Y90Source/gps/histpoint	0.007		0.3391
/gate/source/Y90Source/gps/histpoint	0.0075		0.3394
/gate/source/Y90Source/gps/histpoint	0.008		0.3398
/gate/source/Y90Source/gps/histpoint	0.0085		0.3401
/gate/source/Y90Source/gps/histpoint	0.009		0.3404
/gate/source/Y90Source/gps/histpoint	0.01		0.341
/gate/source/Y90Source/gps/histpoint	0.011		0.3416
/gate/source/Y90Source/gps/histpoint	0.012		0.3422
/gate/source/Y90Source/gps/histpoint	0.013		0.3428
/gate/source/Y90Source/gps/histpoint	0.014		0.3435
/gate/source/Y90Source/gps/histpoint	0.015		0.3441
/gate/source/Y90Source/gps/histpoint	0.016		0.3447
/gate/source/Y90Source/gps/histpoint	0.018		0.3459
/gate/source/Y90Source/gps/histpoint	0.02		0.3472
/gate/source/Y90Source/gps/histpoint	0.022		0.3484
/gate/source/Y90Source/gps/histpoint	0.024		0.3497
/gate/source/Y90Source/gps/histpoint	0.026		0.351
/gate/source/Y90Source/gps/histpoint	0.028		0.3523
/gate/source/Y90Source/gps/histpoint	0.03		0.3536
/gate/source/Y90Source/gps/histpoint	0.032		0.355
/gate/source/Y90Source/gps/histpoint	0.036		0.3577
/gate/source/Y90Source/gps/histpoint	0.04		0.3605
/gate/source/Y90Source/gps/histpoint	0.045		0.3641
/gate/source/Y90Source/gps/histpoint	0.05		0.3677
/gate/source/Y90Source/gps/histpoint	0.055		0.3713
/gate/source/Y90Source/gps/histpoint	0.06		0.375
/gate/source/Y90Source/gps/histpoint	0.065		0.3788
/gate/source/Y90Source/gps/histpoint	0.07		0.3825
/gate/source/Y90Source/gps/histpoint	0.075		0.3863
/gate/source/Y90Source/gps/histpoint	0.08		0.39
/gate/source/Y90Source/gps/histpoint	0.085		0.3938
/gate/source/Y90Source/gps/histpoint	0.09		0.3975
/gate/source/Y90Source/gps/histpoint	0.1		0.405
/gate/source/Y90Source/gps/histpoint	0.11		0.4124
/gate/source/Y90Source/gps/histpoint	0.12		0.4197
/gate/source/Y90Source/gps/histpoint	0.13		0.4269
/gate/source/Y90Source/gps/histpoint	0.14		0.434
/gate/source/Y90Source/gps/histpoint	0.15		0.441
/gate/source/Y90Source/gps/histpoint	0.16		0.4479
/gate/source/Y90Source/gps/histpoint	0.18		0.4612
/gate/source/Y90Source/gps/histpoint	0.2		0.474
/gate/source/Y90Source/gps/histpoint	0.22		0.4862
/gate/source/Y90Source/gps/histpoint	0.24		0.4978
/gate/source/Y90Source/gps/histpoint	0.26		0.5089
/gate/source/Y90Source/gps/histpoint	0.28		0.5194
/gate/source/Y90Source/gps/histpoint	0.3		0.5294
/gate/source/Y90Source/gps/histpoint	0.32		0.5387
/gate/source/Y90Source/gps/histpoint	0.36		0.5559
/gate/source/Y90Source/gps/histpoint	0.4		0.5709
/gate/source/Y90Source/gps/histpoint	0.45		0.5868
/gate/source/Y90Source/gps/histpoint	0.5		0.5998
/gate/source/Y90Source/gps/histpoint	0.55		0.6102
/gate/source/Y90Source/gps/histpoint	0.6		0.6181
/gate/source/Y90Source/gps/histpoint	0.65		0.6238
/gate/source/Y90Source/gps/histpoint	0.7		0.6274
/gate/source/Y90Source/gps/histpoint	0.75		0.6292
/gate/source/Y90Source/gps/histpoint	0.8		0.6292
/gate/source/Y90Source/gps/histpoint	0.85		0.6276
/gate/source/Y90Source/gps/histpoint	0.9		0.6245
/gate/source/Y90Source/gps/histpoint	1		0.6141
/gate/source/Y90Source/gps/histpoint	1.1		0.5979
/gate/source/Y90Source/gps/histpoint	1.2		0.5756
/gate/source/Y90Source/gps/histpoint	1.3		0.5466
/gate/source/Y90Source/gps/histpoint	1.4		0.5099
/gate/source/Y90Source/gps/histpoint	1.5		0.4647
/gate/source/Y90Source/gps/histpoint	1.6		0.4105
/gate/source/Y90Source/gps/histpoint	1.8		0.2271
/gate/source/Y90Source/gps/histpoint	2		0.1276
/gate/source/Y90Source/gps/histpoint	2.2		0.01403
/gate/source/Y90Source/gps/histpoint	2.2801		0

#/gate/source/Y90Source/gps/arbint               Spline

/gate/source/Y90Source/gps/confine		my_phantom_phys
#/gate/source/Y90Source/attachTo my_phantom
/gate/source/Y90Source/dump 1
