# GATE Monte Carlo dose estimation using source: 15keV monoenergetic electrons in spherical water phantom #
# Absorbed dose estimation macros #
# Written by: Ashok Tiwari, July 30, 2018 #
# PET Center, University of Iowa Hospitals and Clinics #


#---------------------------------------------------------------------#
#              1.   V E R B O S I T Y                                 #
#---------------------------------------------------------------------#
/gate/verbose Physic    0
/gate/verbose Cuts	0
/gate/verbose SD        0
/gate/verbose Actions   0
/gate/verbose Actor     1
/gate/verbose Step	1
/gate/verbose Error     1
/gate/verbose Warning   1
/gate/verbose Output    1
/gate/verbose Beam	0
/gate/verbose Volume    0
/gate/verbose Image     0
/gate/verbose Geometry  0
/gate/verbose Core	0

/run/verbose 2
/event/verbose 2
/tracking/verbose 2

/gate/geometry/setMaterialDatabase /Users/atiwr/gate_data_files/GateMaterials.db

#----------------------------------------------------------------------#
#                       2.    W O R L D                                #
#----------------------------------------------------------------------#
/gate/world/geometry/setXLength 	1 cm
/gate/world/geometry/setYLength 	1 cm
/gate/world/geometry/setZLength 	1 cm
/gate/world/setMaterial                 Water

#----------------------------------------------------------------------#
#             3.  P H A N T O M   G E O M E T R Y                      #
#----------------------------------------------------------------------#
/gate/world/daughters/name              my_phantom
/gate/world/daughters/insert            sphere
/gate/my_phantom/setMaterial            Water    

/gate/my_phantom/geometry/setRmax	0.0213 mm  
/gate/my_phantom/geometry/setRmin	0.0 mm
/gate/my_phantom/vis/forceSolid
/gate/my_phantom/vis/setColor           grey
/gate/my_phantom/placement/setTranslation 0 0 0 mm
/gate/my_phantom/attachPhantomSD

#----------------------------------------------------------------------#
#             4.    A C T O R S                                        #
#----------------------------------------------------------------------#

/gate/actor/addActor DoseActor              dosimetry
/gate/actor/dosimetry/attachTo              my_phantom
/gate/actor/dosimetry/stepHitType           random  #post

/gate/actor/dosimetry/setSize               0.0426 0.0426 0.0426 mm
#/gate/actor/dosimetry/setResolution        400 400 400
/gate/actor/dosimetry/setVoxelSize          0.0001065 0.0001065 0.0001065 mm   
/gate/actor/dosimetry/setPosition           0.0 0.0 0.0 mm

/gate/actor/dosimetry/enableDose            false
/gate/actor/dosimetry/enableEdep            true
/gate/actor/dosimetry/enableUncertaintyEdep false
/gate/actor/dosimetry/enableSquaredEdep     false
/gate/actor/dosimetry/save                  output/2e7_water_15keV.mhd
/gate/actor/dosimetry/saveEveryNSeconds     100

/gate/actor/addActor                        SimulationStatisticActor stat
/gate/actor/stat/save                       output/2e7_water_15KeV.txt
/gate/actor/stat/saveEveryNSeconds          100

#----------------------------------------------------------------------#
#             5.  P H Y S I C S                                        #
#----------------------------------------------------------------------#
/gate/physics/addPhysicsList  emstandard_opt3

#/gate/physics/addProcess RayleighScattering
#/gate/physics/processes/RayleighScattering/setModel PenelopeModel

#/gate/physics/addProcess GammaConversion
#/gate/physics/processes/GammaConversion/setModel StandardModel


#----------------------------------------------------------------------#
#         6. E L E C T R O M A G N E T I C    O P T I O N S            #
#----------------------------------------------------------------------#
/gate/physics/setEMin 0.1 keV
/gate/physics/setEMax 10 GeV
/gate/physics/setDEDXBinning   220
/gate/physics/setLambdaBinning 220

# Production Threshold cut: to avoid infrared divergence cut, 
# below this threshold no secondary particles will be generated.

/gate/physics/Gamma/SetCutInRegion	world 0.1 mm
/gate/physics/Electron/SetCutInRegion   world 0.005 mm

/gate/physics/Gamma/SetCutInRegion	my_phantom 0.1 mm
/gate/physics/Electron/SetCutInRegion   my_phantom 0.002 mm

# Step-Limiter
/gate/physics/SetMaxStepSizeInRegion my_phantom 0.0001065 mm 
/gate/physics/ActivateStepLimiter e-

/gate/physics/processes/ElectronIonisation/setStepFunction e- 0.0001 0.001 mm   

#----------------------------------------------------------------------#
#                 7.  I N I T I A L I Z E                              #
#----------------------------------------------------------------------#
/gate/run/initialize
/gate/physics/displayCuts
/gate/physics/processList Enabled
/gate/physics/processList Initialized

#----------------------------------------------------------------------#
#             8.  S O U R C E   D E F I N I T I O N                   #
#----------------------------------------------------------------------#
/gate/source/addSource  monoenergetic_electron                  gps
/gate/source/monoenergetic_electron/gps/particle                e-
/gate/source/monoenergetic_electron/gps/energytype              Mono
/gate/source/monoenergetic_electron/gps/monoenergy              15.0 keV

/gate/source/monoenergetic_electron/setActivity 		500000000. becquerel

/gate/source/monoenergetic_electron/gps/angtype                 iso
/gate/source/monoenergetic_electron/gps/mintheta                0 deg
/gate/source/monoenergetic_electron/gps/maxtheta                180 deg
/gate/source/monoenergetic_electron/gps/minphi                  0 deg
/gate/source/monoenergetic_electron/gps/maxphi                  360 deg
/gate/source/monoenergetic_electron/gps/centre                  0 0 0 mm
/gate/source/monoenergetic_electron/gps/type                    Point

/gate/source/monoenergetic_electron/attachTo                    my_phantom
/gate/source/monoenergetic_electron/visualize                   100 yellow 2   
/gate/source/list

#-----------------------------------------------------------------------#
#        9.  R A N D O M     G E N E R A T O R                         #
#-----------------------------------------------------------------------#
/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto

#-----------------------------------------------------------------------#
#	10.   S T A R T   S I M U L A T I O N                           #
#-----------------------------------------------------------------------#
/gate/application/setTotalNumberOfPrimaries 2e7
/gate/application/start




