# GATE Monte Carlo dose estimation using the beta spectrum of Re-188 in spherical blood phantom #

#---------------------------------------------------------------------#
#                 V E R B O S I T Y                                   #
#---------------------------------------------------------------------#
/gate/verbose Physic    0
/gate/verbose Cuts	0
/gate/verbose SD        0
/gate/verbose Actions   0
/gate/verbose Actor     0
/gate/verbose Step	0
/gate/verbose Error     0
/gate/verbose Warning   0
/gate/verbose Output    0
/gate/verbose Beam	0
/gate/verbose Volume    0
/gate/verbose Image     0
/gate/verbose Geometry  0
/gate/verbose Core	0

/run/verbose 2
/event/verbose 2
/tracking/verbose 2

/gate/geometry/setMaterialDatabase  GateMaterials.db
#----------------------------------------------------------------------#
#                  W O R L D                                           #
#----------------------------------------------------------------------#
/gate/world/geometry/setXLength         10 cm
/gate/world/geometry/setYLength         10 cm
/gate/world/geometry/setZLength         10 cm
/gate/world/setMaterial                 Water

#----------------------------------------------------------------------#
#            P H A N T O M   G E O M E T R Y                           #
#----------------------------------------------------------------------#
/gate/world/daughters/name              my_phantom
/gate/world/daughters/insert            sphere
/gate/my_phantom/setMaterial            Blood

/gate/my_phantom/geometry/setRmax	22.60 mm
/gate/my_phantom/geometry/setRmin	0.   mm
/gate/my_phantom/vis/forceSolid
/gate/my_phantom/vis/setColor           grey
/gate/my_phantom/placement/setTranslation 0 0 0 mm
/gate/my_phantom/attachPhantomSD

#----------------------------------------------------------------------#
#               A C T O R S                                            #
#----------------------------------------------------------------------#
/gate/actor/addActor          DoseActor    dosimetry
/gate/actor/dosimetry/attachTo             my_phantom
/gate/actor/dosimetry/stepHitType          post

#/gate/actor/dosimetry/setResolution	   500 500 500
/gate/actor/dosimetry/setPosition          -0.045045 -0.045045 -0.045045 mm
/gate/actor/dosimetry/setSize              45.045 45.045 45.045 mm
/gate/actor/dosimetry/setVoxelSize         0.09009 0.09009 0.09009 mm

/gate/actor/dosimetry/enableDose            false
/gate/actor/dosimetry/enableEdep            true
/gate/actor/dosimetry/enableUncertaintyEdep true
/gate/actor/dosimetry/enableSquaredEdep     true
/gate/actor/dosimetry/save                  output/2e7_Re188_blood.mhd
/gate/actor/dosimetry/saveEveryNSeconds     120

/gate/actor/addActor                        SimulationStatisticActor stat
/gate/actor/stat/save                       output/2e7_Re188_blood_stats.txt
/gate/actor/stat/saveEveryNSeconds          120


#----------------------------------------------------------------------#
#             P H Y S I C S   D E S C R I P T I O N                    #
#----------------------------------------------------------------------#
/gate/physics/addPhysicsList  emstandard_opt3

/gate/physics/addProcess RayleighScattering
/gate/physics/processes/RayleighScattering/setModel PenelopeModel

# ---------------------------------------------------------------------#
#		 ELECTROMAGNETIC OPTIONS 			       #
#----------------------------------------------------------------------#
/gate/physics/setEMin 0.1 keV
/gate/physics/setEMax 10 GeV
/gate/physics/setDEDXBinning   220
/gate/physics/setLambdaBinning 220

/gate/physics/Gamma/SetCutInRegion	world 0.1 mm          # 1 keV cut in water
/gate/physics/Electron/SetCutInRegion   world 0.01 mm         # keV cut in water

/gate/physics/Gamma/SetCutInRegion	my_phantom 0.1 mm     # 1.13 keV cut in blood
/gate/physics/Electron/SetCutInRegion   my_phantom 0.006 mm   #  keV energy cut in blood

/gate/physics/SetMaxStepSizeInRegion    my_phantom 0.09009 mm
/gate/physics/ActivateStepLimiter e-

/gate/physics/processes/ElectronIonisation/setStepFunction e- 0.0001  0.001 mm

#----------------------------------------------------------------------#
#                     I N I T I A L I Z E                              #
#----------------------------------------------------------------------#
/gate/run/initialize
/gate/physics/displayCuts
/gate/physics/processList Enabled
/gate/physics/processList Initialized

#----------------------------------------------------------------------#
#           Beta spectrum : Discrete spectrum                          #
#----------------------------------------------------------------------#
/gate/source/addSource Re188spectrum            gps
/gate/source/Re188spectrum/attachTo             my_phantom
/gate/source/Re188spectrum/gps/particle         e-

/gate/source/Re188spectrum/gps/angtype          iso
/gate/source/Re188spectrum/gps/energytype	Arb
/gate/source/Re188spectrum/setIntensity         1
/gate/source/Re188spectrum/gps/histname         arb
/gate/source/Re188spectrum/gps/position         0 0 0 mm
/gate/source/Re188spectrum/gps/type             Point

######################################### Energy(MeV) ##### Intensity #
/gate/source/Re188spectrum/gps/hist/point 0             0.0
/gate/source/Re188spectrum/gps/hist/point 0.1060        5.69E-02
/gate/source/Re188spectrum/gps/hist/point 0.2119        6.37E-02
/gate/source/Re188spectrum/gps/hist/point 0.3179        7.04E-02
/gate/source/Re188spectrum/gps/hist/point 0.4239        7.57E-02
/gate/source/Re188spectrum/gps/hist/point 0.5299        7.93E-02
/gate/source/Re188spectrum/gps/hist/point 0.6358        8.09E-02
/gate/source/Re188spectrum/gps/hist/point 0.7418        8.07E-02
/gate/source/Re188spectrum/gps/hist/point 0.8478        7.86E-02
/gate/source/Re188spectrum/gps/hist/point 0.9537        7.47E-02
/gate/source/Re188spectrum/gps/hist/point 1.0597        6.92E-02
/gate/source/Re188spectrum/gps/hist/point 1.1657        6.24E-02
/gate/source/Re188spectrum/gps/hist/point 1.2716        5.46E-02
/gate/source/Re188spectrum/gps/hist/point 1.3776        4.60E-02
/gate/source/Re188spectrum/gps/hist/point 1.4836        3.71E-02
/gate/source/Re188spectrum/gps/hist/point 1.5896        2.82E-02
/gate/source/Re188spectrum/gps/hist/point 1.6955        1.99E-02
/gate/source/Re188spectrum/gps/hist/point 1.8015        1.23E-02
/gate/source/Re188spectrum/gps/hist/point 1.9075        6.53E-03
/gate/source/Re188spectrum/gps/hist/point 2.0134        2.34E-03
/gate/source/Re188spectrum/gps/hist/point 2.1194        4.03E-04

/gate/source/Re188spectrum/gps/arbint Lin     # Spline

# first column is energy in MeV and second is intensity
# Reference: doseinfo-radar.com/BetaSpec.zip

#/gate/source/Re188spectrum/visualize           100 red 3
/gate/source/list

#----------------------------------------------------------------------#
#               V I S U A L I S A T I O N                              #
#----------------------------------------------------------------------#
#/vis/disable

/vis/open OGLSQt
/vis/viewer/reset
/vis/viewer/set/viewpointThetaPhi 30 60
/vis/viewer/zoom
/vis/viewer/set/style wireframe
/vis/drawVolume
/vis/viewer/flush
/vis/scene/add/trajectories
/tracking/storeTrajectory 1
#-----------------------------------------------------------------------#
#          R A N D O M     G E N E R A T O R                            #
#-----------------------------------------------------------------------#
/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto
/gate/random/verbose 2

#-----------------------------------------------------------------------#
#          S T A R T   S I M U L A T I O N                              #
#-----------------------------------------------------------------------#
/gate/application/setTotalNumberOfPrimaries 2e7
/gate/application/start


