# GATE Monte Carlo dose estimation using source: 15keV monoenergetic electrons in spherical bone phantom #
# Absorbed dose estimation macros #
# Written by: Ashok Tiwari, Feb 13, 2019 #
# PET Center, University of Iowa Hospitals and Clinics #


#---------------------------------------------------------------------#
#              1.   V E R B O S I T Y                                 #
#---------------------------------------------------------------------#
/gate/verbose Physic    0
/gate/verbose Cuts      0
/gate/verbose SD        0
/gate/verbose Actions   0
/gate/verbose Actor     0
/gate/verbose Step	0
/gate/verbose Error     0
/gate/verbose Warning   0
/gate/verbose Output    0
/gate/verbose Beam	0
/gate/verbose Volume    0
/gate/verbose Image     0
/gate/verbose Geometry  0
/gate/verbose Core	0

/run/verbose 2
/event/verbose 2
/tracking/verbose 2

/gate/geometry/setMaterialDatabase /Users/atiwr/gate_data_files/GateMaterials.db

#----------------------------------------------------------------------#
#                       2.    W O R L D                                #
#----------------------------------------------------------------------#
/gate/world/geometry/setXLength 	1 cm
/gate/world/geometry/setYLength 	1 cm
/gate/world/geometry/setZLength 	1 cm
/gate/world/setMaterial         	Water

#----------------------------------------------------------------------#
#             3.  P H A N T O M   G E O M E T R Y                      #
#----------------------------------------------------------------------#
/gate/world/daughters/name              my_phantom
/gate/world/daughters/insert            sphere
/gate/my_phantom/setMaterial            CompactBone     # set material

# Sphere radius = # of shells times dosel size
/gate/my_phantom/geometry/setRmax	0.01062 mm     # radius = setSize/2
/gate/my_phantom/geometry/setRmin	0. mm
/gate/my_phantom/vis/forceSolid
/gate/my_phantom/vis/setColor           grey
/gate/my_phantom/placement/setTranslation 0 0 0 mm
/gate/my_phantom/attachPhantomSD

#----------------------------------------------------------------------#
#             4.    A C T O R S                                        #
#----------------------------------------------------------------------#

/gate/actor/addActor DoseActor              dosimetry
/gate/actor/dosimetry/attachTo              my_phantom
/gate/actor/dosimetry/stepHitType           post

/gate/actor/dosimetry/setSize               0.02124 0.02124 0.02124 mm
#/gate/actor/dosimetry/setResolution        400 400 400
/gate/actor/dosimetry/setVoxelSize          0.00005310 0.00005310 0.00005310 mm   
/gate/actor/dosimetry/setPosition           0 0 0 mm

/gate/actor/dosimetry/enableDose            false
/gate/actor/dosimetry/enableEdep            true
/gate/actor/dosimetry/enableUncertaintyEdep true
/gate/actor/dosimetry/enableSquaredEdep     true
/gate/actor/dosimetry/save                  output/2e7_bone_15keV.mhd
/gate/actor/dosimetry/saveEveryNSeconds     200

/gate/actor/addActor                        SimulationStatisticActor stat
/gate/actor/stat/save                       output/2e7_bone_15keV_stats.txt
/gate/actor/stat/saveEveryNSeconds          200

#----------------------------------------------------------------------#
#             5.  P H Y S I C S                                        #
#----------------------------------------------------------------------#
/gate/physics/addPhysicsList  emstandard_opt3

#/gate/physics/addProcess RayleighScattering
#/gate/physics/processes/RayleighScattering/setModel LivermoreModel

#----------------------------------------------------------------------#
#         6. E L E C T R O M A G N E T I C    O P T I O N S            #
#----------------------------------------------------------------------#
/gate/physics/setEMin 0.1 keV
/gate/physics/setEMax 10 GeV
/gate/physics/setDEDXBinning   220
/gate/physics/setLambdaBinning 220


# Production Threshold cut: to avoid infrared divergence cut, 
# below this threshold no secondary particles will be generated.

/gate/physics/Gamma/SetCutInRegion	world 0.1 mm
/gate/physics/Electron/SetCutInRegion   world 0.0081 mm

/gate/physics/Gamma/SetCutInRegion	my_phantom 0.1 mm
/gate/physics/Electron/SetCutInRegion   my_phantom 0.002 mm 

# Step-Limiter
/gate/physics/SetMaxStepSizeInRegion my_phantom 0.00005310 mm 
/gate/physics/ActivateStepLimiter e-

/gate/physics/processes/ElectronIonisation/setStepFunction e- 0.001  0.001 m   


#----------------------------------------------------------------------#
#                 7.  I N I T I A L I Z E                              #
#----------------------------------------------------------------------#
/gate/run/initialize
/gate/physics/displayCuts
/gate/physics/processList Enabled
/gate/physics/processList Initialized


#----------------------------------------------------------------------#
#             8.  S O U R C E   D E F I N I T I O N                   #
#----------------------------------------------------------------------#
/gate/source/addSource  monoenergetic_electron                  gps
/gate/source/monoenergetic_electron/gps/particle                e-
/gate/source/monoenergetic_electron/gps/energytype              Mono
/gate/source/monoenergetic_electron/gps/ene/mono                15 keV
/gate/source/monoenergetic_electron/gps/angtype                 iso
/gate/source/monoenergetic_electron/gps/centre                  0. 0. 0. mm
/gate/source/monoenergetic_electron/gps/type                    Point

/gate/source/monoenergetic_electron/attachTo                    my_phantom
/gate/source/monoenergetic_electron/visualize                   100 yellow 2
/gate/source/list

#----------------------------------------------------------------------#
#            10.   V I S U A L I S A T I O N                            #
#----------------------------------------------------------------------#
/vis/disable

/vis/open OGLIQt
/vis/viewer/reset
/vis/viewer/set/viewpointThetaPhi 30 60
/vis/viewer/zoom
/vis/viewer/set/style wireframe
/vis/drawVolume
/vis/viewer/flush
/vis/scene/add/trajectories
/tracking/storeTrajectory 1
/vis/scene/add/hits
/vis/scene/endOfEventAction accumulate 10


#-----------------------------------------------------------------------#
#        11.  R A N D O M     G E N E R A T O R                         #
#-----------------------------------------------------------------------#

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto

#-----------------------------------------------------------------------#
#	12.   S T A R T   S I M U L A T I O N                           #
#-----------------------------------------------------------------------#
/gate/application/setTotalNumberOfPrimaries 2e7
/gate/application/start




