# GATE Monte Carlo dose estimation using beta spectrum of  Lu-177 in spherical adipose phantom #

#---------------------------------------------------------------------#
#                 V E R B O S I T Y                                   #
#---------------------------------------------------------------------#
/gate/verbose Physic    0
/gate/verbose Cuts      0
/gate/verbose SD        0
/gate/verbose Actions   0
/gate/verbose Actor     0
/gate/verbose Step      0
/gate/verbose Error     0
/gate/verbose Warning   0
/gate/verbose Output    0
/gate/verbose Beam      0
/gate/verbose Volume    0
/gate/verbose Image     0
/gate/verbose Geometry  0
/gate/verbose Core      0

/run/verbose 2
/event/verbose 2
/tracking/verbose 2

/gate/geometry/setMaterialDatabase /Users/atiwr/gate_data_files/GateMaterials.db
#----------------------------------------------------------------------#
#                          W O R L D                                   #
#----------------------------------------------------------------------#
/gate/world/geometry/setXLength         8 mm
/gate/world/geometry/setYLength         8 mm
/gate/world/geometry/setZLength         8 mm
/gate/world/setMaterial                 Water

#----------------------------------------------------------------------#
#            P H A N T O M         G E O M E T R Y                     #
#----------------------------------------------------------------------#
/gate/world/daughters/name              my_phantom
/gate/world/daughters/insert            sphere
/gate/my_phantom/setMaterial            Adipose         # d = 0.92 g/cm3

/gate/my_phantom/geometry/setRmax       3.63 mm
/gate/my_phantom/geometry/setRmin       0.   mm
/gate/my_phantom/vis/forceSolid
/gate/my_phantom/vis/setColor           grey
/gate/my_phantom/placement/setTranslation 0 0 0 mm

/gate/my_phantom/attachPhantomSD
# sphere radius = dosel size * # of concentric shells

#----------------------------------------------------------------------#
#               A C T O R S                                            #
#----------------------------------------------------------------------#
/gate/actor/addActor          DoseActor    dosimetry
/gate/actor/dosimetry/attachTo             my_phantom
/gate/actor/dosimetry/stepHitType          post

#/gate/actor/dosimetry/setResolution       600 600 600
/gate/actor/dosimetry/setPosition          0 0 0 mm
/gate/actor/dosimetry/setSize 	           7.26 7.26 7.26 mm
/gate/actor/dosimetry/setVoxelSize         0.0121 0.0121 0.0121 mm

/gate/actor/dosimetry/enableDose            false
/gate/actor/dosimetry/enableEdep            true
/gate/actor/dosimetry/enableUncertaintyEdep true
/gate/actor/dosimetry/enableSquaredEdep     true
/gate/actor/dosimetry/save                  output/2e7_Lu177_adipose.mhd
/gate/actor/dosimetry/saveEveryNSeconds     200

/gate/actor/addActor                        SimulationStatisticActor stat
/gate/actor/stat/save                       output/2e7_Lu177_adipose.txt
/gate/actor/stat/saveEveryNSeconds          200

#----------------------------------------------------------------------#
#             P H Y S I C S   D E S C R I P T I O N                    #
#----------------------------------------------------------------------#
/gate/physics/addPhysicsList  emstandard_opt3

/gate/physics/addProcess RayleighScattering
/gate/physics/processes/RayleighScattering/setModel PenelopeModel

# ---------------------------------------------------------------------#
#    ELECTROMAGNETIC    OPTIONS                                        #
#----------------------------------------------------------------------#
/gate/physics/setEMin 0.1 keV
/gate/physics/setEMax 10 GeV
/gate/physics/setDEDXBinning   220
/gate/physics/setLambdaBinning 220

/gate/physics/Gamma/SetCutInRegion      world 0.1 mm
/gate/physics/Electron/SetCutInRegion   world 0.005 mm

/gate/physics/Gamma/SetCutInRegion      my_phantom 0.1 mm
/gate/physics/Electron/SetCutInRegion   my_phantom 0.004 mm

/gate/physics/SetMaxStepSizeInRegion    my_phantom 0.0121 mm
/gate/physics/ActivateStepLimiter e-

/gate/physics/processes/ElectronIonisation/setStepFunction e- 0.0001  0.001 mm

#----------------------------------------------------------------------#
#                     I N I T I A L I Z E                              #
#----------------------------------------------------------------------#
/gate/run/initialize
/gate/physics/displayCuts
/gate/physics/processList Enabled
/gate/physics/processList Initialized

#----------------------------------------------------------------------#
#           Beta spectrum : Discrete spectrum                          #
#----------------------------------------------------------------------#
/gate/source/addSource Lu177spectrum            gps
/gate/source/Lu177spectrum/attachTo             my_phantom
/gate/source/Lu177spectrum/gps/particle         e-

/gate/source/Lu177spectrum/gps/angtype          iso
/gate/source/Lu177spectrum/gps/energytype	Arb
/gate/source/Lu177spectrum/setIntensity         1
/gate/source/Lu177spectrum/gps/histname         arb
/gate/source/Lu177spectrum/gps/position         0 0 0 mm
/gate/source/Lu177spectrum/gps/type             Point

######################################### Energy(MeV) ##### Intensity #
/gate/source/Lu177spectrum/gps/hist/point 0             0.0
/gate/source/Lu177spectrum/gps/hist/point 0.0249        1.35E-01
/gate/source/Lu177spectrum/gps/hist/point 0.0497        1.22E-01
/gate/source/Lu177spectrum/gps/hist/point 0.0746        1.09E-01
/gate/source/Lu177spectrum/gps/hist/point 0.0994        9.68E-02
/gate/source/Lu177spectrum/gps/hist/point 0.1243        8.51E-02
/gate/source/Lu177spectrum/gps/hist/point 0.1491        7.45E-02
/gate/source/Lu177spectrum/gps/hist/point 0.1740        6.57E-02
/gate/source/Lu177spectrum/gps/hist/point 0.1988        5.88E-02
/gate/source/Lu177spectrum/gps/hist/point 0.2237        5.22E-02
/gate/source/Lu177spectrum/gps/hist/point 0.2485        4.56E-02
/gate/source/Lu177spectrum/gps/hist/point 0.2734        3.89E-02
/gate/source/Lu177spectrum/gps/hist/point 0.2983        3.24E-02
/gate/source/Lu177spectrum/gps/hist/point 0.3231        2.61E-02
/gate/source/Lu177spectrum/gps/hist/point 0.3480        2.03E-02
/gate/source/Lu177spectrum/gps/hist/point 0.3728        1.50E-02
/gate/source/Lu177spectrum/gps/hist/point 0.3977        1.05E-02
/gate/source/Lu177spectrum/gps/hist/point 0.4225        6.64E-03
/gate/source/Lu177spectrum/gps/hist/point 0.4474        3.46E-03
/gate/source/Lu177spectrum/gps/hist/point 0.4722        1.48E-03
/gate/source/Lu177spectrum/gps/hist/point 0.4971        2.97E-04

/gate/source/Lu177spectrum/gps/arbint Lin	# Spline

# first column is energy in MeV and second is intensity
# Refrence: doseinfo-radar.com/BetaSpec.zip
#/gate/source/Lu177spectrum/visualize           100 red 3
#/gate/source/Lu177spectrum/gps/confine         my_phantom

/gate/source/list
#----------------------------------------------------------------------#
#               V I S U A L I S A T I O N                              #
#----------------------------------------------------------------------#
/vis/disable
/vis/open OGL
/vis/viewer/reset
/vis/viewer/set/viewpointThetaPhi 30 60
/vis/viewer/zoom
/vis/viewer/set/style wireframe
/vis/drawVolume
/vis/viewer/flush
/vis/scene/add/trajectories
/tracking/storeTrajectory 1
/vis/scene/add/hits
/vis/scene/endOfEventAction accumulate 10

#-----------------------------------------------------------------------#
#          R A N D O M     G E N E R A T O R                            #
#-----------------------------------------------------------------------#
/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto
/gate/random/verbose 2

#-----------------------------------------------------------------------#
#          S T A R T   S I M U L A T I O N                              #
#-----------------------------------------------------------------------#
/gate/application/setTotalNumberOfPrimaries 2e7
/gate/application/start

